In [1]:
import numpy as np
from matplotlib import pyplot

In [2]:
state_space = np.array([0,1,2,3,4,5])
action_space = np.array([0,1])

In [3]:
reward_matrix = np.zeros((6,2))

In [4]:
reward_matrix[0,0] = 50 # 50 - 2x0
reward_matrix[1,0] = 48 # 50 - 2x1
reward_matrix[2,0] = 42 # 50 - 2x4
reward_matrix[3,0] = 32 # 50 - 2x9
reward_matrix[4,0] = 18 # 50 - 2x16
reward_matrix[5,0] = 0
reward_matrix[0,1] = -100
reward_matrix[1,1] = -100
reward_matrix[2,1] = -100
reward_matrix[3,1] = -100
reward_matrix[4,1] = -100
reward_matrix[5,1] = -100

In [5]:
transition_probability_matrix = np.zeros((2,6,6))
t = np.array([[0.7, 0.3, 0, 0, 0, 0], [0, 0.6, 0.4, 0, 0, 0], [0, 0, 0.5, 0.5, 0, 0], [0, 0, 0, 0.4, 0.6, 0], [0, 0, 0, 0, 0.3, 0.7], [0, 0, 0, 0, 0, 1]])
transition_probability_matrix[0, :, :] = t
t = np.array([[1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0]])
transition_probability_matrix[1, :, :] = t

In [6]:
transition_probability_matrix

array([[[0.7, 0.3, 0. , 0. , 0. , 0. ],
        [0. , 0.6, 0.4, 0. , 0. , 0. ],
        [0. , 0. , 0.5, 0.5, 0. , 0. ],
        [0. , 0. , 0. , 0.4, 0.6, 0. ],
        [0. , 0. , 0. , 0. , 0.3, 0.7],
        [0. , 0. , 0. , 0. , 0. , 1. ]],

       [[1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ]]])

In [7]:
class MachineRepair_Environment:
    def __init__(self, transition_probability_matrix, reward_matrix, initial_state):
        self.transition_probability_matrix = transition_probability_matrix
        self.reward_matrix = reward_matrix
        self.current_state = initial_state
    
    def get_current_state(self):
        return self.current_state
        
    def run_one_step(self, action):
        transition_probability = transition_probability_matrix[action, self.current_state, :]
        # obtain the reward
        reward = reward_matrix[self.current_state, action]
        # update the state
        next_state = np.random.choice(state_space, p = transition_probability)
        self.current_state = next_state
        return [next_state, reward]
        

In [14]:
num_episodes = 5000
horizon = 100
discount_factor = 0.8
epsilon = 0.1 # for epsilon-greedy policy

every_visit_estimate = np.zeros([len(state_space),len(action_space)])
every_visit_count = np.zeros([len(state_space),len(action_space)])

for e in range(num_episodes):
    initial_state = np.random.choice(state_space) # with exploring starts
    # initial_state = 0
    environment = MachineRepair_Environment(transition_probability_matrix, reward_matrix, initial_state)
    state_sequence = []
    action_sequence = []
    reward_sequence = []

    for t in range(horizon):
        state = environment.get_current_state()
        state_sequence.append(state)
        if np.random.rand() <= epsilon/(e + 1):
            action = np.random.choice(action_space)
        else:
            action = action_space[np.argmax(every_visit_estimate[state, :])]
        action_sequence.append(action)
        [state, reward] = environment.run_one_step(action)
        reward_sequence.append(reward)
    for t, s in enumerate(state_sequence):
        a = action_sequence[t]
        every_visit_return = sum(reward_sequence[t:] * np.power(discount_factor, range(len(state_sequence) - t)))
        every_visit_count[s, a] = every_visit_count[s, a] + 1.0        
        if every_visit_count[s, a] > 0:
            every_visit_estimate[s, a] = ((every_visit_count[s, a] - 1) * every_visit_estimate[s, a] + \
                                          every_visit_return)/every_visit_count[s, a]            

In [15]:
every_visit_estimate

array([[202.95221738,  68.19481864],
       [170.22062594,  68.07629418],
       [131.100957  ,  57.3330746 ],
       [ 93.74301346,  66.09831954],
       [ 67.63624439,  59.00080294],
       [  7.27110081,  60.76167317]])

In [13]:
every_visit_count

array([[157874.,   8287.],
       [104081.,   5432.],
       [ 75058.,   3962.],
       [ 58013.,   2983.],
       [ 46706.,   2344.],
       [  1887.,  33373.]])