In [1]:
import numpy as np
from matplotlib import pyplot

In [2]:
state_space = np.array([0,1,2,3,4,5])
action_space = np.array([0,1])

In [3]:
reward_matrix = np.zeros((6,2))

In [4]:
reward_matrix[0,0] = 50 # 50 - 2x0
reward_matrix[1,0] = 48 # 50 - 2x1
reward_matrix[2,0] = 42 # 50 - 2x4
reward_matrix[3,0] = 32 # 50 - 2x9
reward_matrix[4,0] = 18 # 50 - 2x16
reward_matrix[5,0] = 0
reward_matrix[0,1] = -100
reward_matrix[1,1] = -100
reward_matrix[2,1] = -100
reward_matrix[3,1] = -100
reward_matrix[4,1] = -100
reward_matrix[5,1] = -100

In [5]:
transition_probability_matrix = np.zeros((2,6,6))
t = np.array([[0.7, 0.3, 0, 0, 0, 0], [0, 0.6, 0.4, 0, 0, 0], [0, 0, 0.5, 0.5, 0, 0], [0, 0, 0, 0.4, 0.6, 0], [0, 0, 0, 0, 0.3, 0.7], [0, 0, 0, 0, 0, 1]])
transition_probability_matrix[0, :, :] = t
t = np.array([[1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0]])
transition_probability_matrix[1, :, :] = t

In [6]:
transition_probability_matrix

array([[[0.7, 0.3, 0. , 0. , 0. , 0. ],
        [0. , 0.6, 0.4, 0. , 0. , 0. ],
        [0. , 0. , 0.5, 0.5, 0. , 0. ],
        [0. , 0. , 0. , 0.4, 0.6, 0. ],
        [0. , 0. , 0. , 0. , 0.3, 0.7],
        [0. , 0. , 0. , 0. , 0. , 1. ]],

       [[1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ]]])

In [7]:
initial_state = 1

In [8]:
time_horizon = 100
discount_factor = 0.8

In [9]:
old_value_function = np.zeros(6)
new_value_function = np.zeros(6)
policy_function = np.array([0,0,0,1,0,1])

In [23]:
for t in range(1, time_horizon + 1):
    for s in state_space:
        a = policy_function[s]
        new_value_function[s] = reward_matrix[s, a] + discount_factor * np.sum(transition_probability_matrix[a, s, :] * old_value_function)
    old_value_function = new_value_function.copy()

In [24]:
new_value_function

array([201.10732535, 160.36342984, 110.59057351,  60.88586028,
        68.54747598,  60.88586028])

In [25]:
old_value_function

array([201.10732535, 160.36342984, 110.59057351,  60.88586028,
        68.54747598,  60.88586028])