In [1]:
import numpy as np
from matplotlib import pyplot

In [2]:
state_space = np.array([0,1,2,3,4,5])
action_space = np.array([0,1])

In [3]:
reward_matrix = np.zeros((6,2))

In [22]:
reward_matrix[0,0] = 50 # 50 - 2x0
reward_matrix[1,0] = 48 # 50 - 2x1
reward_matrix[2,0] = 42 # 50 - 2x4
reward_matrix[3,0] = 32 # 50 - 2x9
reward_matrix[4,0] = 18 # 50 - 2x16
reward_matrix[5,0] = 0
reward_matrix[0,1] = -10
reward_matrix[1,1] = -20
reward_matrix[2,1] = -30
reward_matrix[3,1] = -40
reward_matrix[4,1] = -100
reward_matrix[5,1] = -100

In [23]:
transition_probability_matrix = np.zeros((2,6,6))
t = np.array([[0.7, 0.3, 0, 0, 0, 0], [0, 0.6, 0.4, 0, 0, 0], [0, 0, 0.5, 0.5, 0, 0], [0, 0, 0, 0.4, 0.6, 0], [0, 0, 0, 0, 0.3, 0.7], [0, 0, 0, 0, 0, 1]])
transition_probability_matrix[0, :, :] = t
t = np.array([[1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0]])
transition_probability_matrix[1, :, :] = t

In [24]:
transition_probability_matrix

array([[[0.7, 0.3, 0. , 0. , 0. , 0. ],
        [0. , 0.6, 0.4, 0. , 0. , 0. ],
        [0. , 0. , 0.5, 0.5, 0. , 0. ],
        [0. , 0. , 0. , 0.4, 0.6, 0. ],
        [0. , 0. , 0. , 0. , 0.3, 0.7],
        [0. , 0. , 0. , 0. , 0. , 1. ]],

       [[1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. , 0. , 0. ]]])

In [25]:
initial_state = 1

In [26]:
time_horizon = 5

In [27]:
value_function = np.zeros((6,time_horizon + 1))
policy_function = np.zeros((6,time_horizon))

In [28]:
for t in range(1, time_horizon + 1):
    for s in state_space:
        max_a = -np.Inf;
        best_action = -1
        for a in action_space:
            metric_a = reward_matrix[s, a] + np.sum(transition_probability_matrix[a, s, :] * value_function[:, t - 1])
            # print(s, a, metric_a)
            if metric_a > max_a:
                max_a = metric_a
                best_action = a
            # print(max_a, best_action)
        policy_function[s, time_horizon - t] = best_action
        value_function[s, t] = max_a

In [29]:
value_function

array([[  0.    ,  50.    ,  99.4   , 147.66  , 194.09  , 237.8158],
       [  0.    ,  48.    ,  93.6   , 135.76  , 173.176 , 204.2216],
       [  0.    ,  42.    ,  79.    , 109.3   , 130.79  , 164.09  ],
       [  0.    ,  32.    ,  55.6   ,  68.28  , 107.66  , 154.09  ],
       [  0.    ,  18.    ,  23.4   ,  25.02  ,  47.66  ,  94.09  ],
       [  0.    ,   0.    ,   0.    ,   0.    ,  47.66  ,  94.09  ]])

In [30]:
policy_function

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])